# Generated by Django 4.0.5 on 2022-07-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
